[tool.bumpversion]
current_version = "0.0.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "chore(release): bump version to {new_version}"
commit = true
message = "chore(release): bump version to {new_version}"

[[tool.bumpversion.files]]
filename = "src/version.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'